AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS PostgreSQL database for Angel Backend'

Parameters:
  ProjectName:
    Type: String
    Default: angel-backend
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  DBName:
    Type: String
    Default: angel_db
    Description: Database name

  DBUsername:
    Type: String
    Default: angel_user
    Description: Database master username
    NoEcho: true

  DBPassword:
    Type: String
    Description: Database master password (min 8 characters)
    NoEcho: true
    MinLength: 8

  DBInstanceClass:
    Type: String
    Default: db.t4g.micro
    AllowedValues:
      - db.t4g.micro
      - db.t4g.small
      - db.t4g.medium
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
    Description: RDS instance class

  DBAllocatedStorage:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 100
    Description: Allocated storage in GB

  DBEngineVersion:
    Type: String
    Default: '17.2'
    Description: PostgreSQL engine version

  MultiAZ:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable Multi-AZ deployment (production recommended)

Resources:
  # DB Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${ProjectName}-${Environment}-db-subnet-group'
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - Fn::ImportValue: !Sub '${ProjectName}-${Environment}-PrivateSubnet1'
        - Fn::ImportValue: !Sub '${ProjectName}-${Environment}-PrivateSubnet2'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db-subnet-group'

  # Security Group for RDS
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-${Environment}-rds-sg'
      GroupDescription: Security group for RDS PostgreSQL
      VpcId:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-VpcId'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId:
            Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ECSTaskSG'
          Description: Allow PostgreSQL from ECS tasks
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-rds-sg'

  # RDS PostgreSQL Instance
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub '${ProjectName}-${Environment}-postgres'
      Engine: postgres
      EngineVersion: !Ref DBEngineVersion
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp3
      StorageEncrypted: true
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      MultiAZ: !Ref MultiAZ
      BackupRetentionPeriod: 7
      PreferredBackupWindow: '03:00-04:00'
      PreferredMaintenanceWindow: 'sun:04:00-sun:05:00'
      EnableCloudwatchLogsExports:
        - postgresql
      DeletionProtection: false
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-postgres'
        - Key: Environment
          Value: !Ref Environment

  # Secrets Manager Secret for Database Credentials
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${Environment}/database'
      Description: Database credentials for Angel Backend
      SecretString: !Sub |
        {
          "username": "${DBUsername}",
          "password": "${DBPassword}",
          "host": "${DBInstance.Endpoint.Address}",
          "port": ${DBInstance.Endpoint.Port},
          "dbname": "${DBName}",
          "engine": "postgres"
        }
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}/${Environment}/database'

Outputs:
  DBInstanceEndpoint:
    Description: RDS instance endpoint address
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DBEndpoint'

  DBInstancePort:
    Description: RDS instance port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DBPort'

  DBName:
    Description: Database name
    Value: !Ref DBName
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DBName'

  DBSecretArn:
    Description: ARN of the Secrets Manager secret containing DB credentials
    Value: !Ref DBSecret
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DBSecretArn'

  DBSecurityGroupId:
    Description: Security Group ID for RDS
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DBSecurityGroupId'
