AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda function to restart ECS service when prompts are updated in S3'

Parameters:
  ProjectName:
    Type: String
    Default: angel-backend
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

Resources:
  # IAM Role for Lambda Function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-prompts-lambda'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ECSServiceRestartPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:UpdateService
                  - ecs:DescribeServices
                Resource:
                  - !Sub
                    - 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/${ClusterName}/${ServiceName}'
                    - ClusterName: !Sub '${ProjectName}-${Environment}-cluster'
                      ServiceName: !Sub '${ProjectName}-${Environment}-backend'
              - Effect: Allow
                Action:
                  - ecs:DescribeClusters
                Resource:
                  - !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ProjectName}-${Environment}-cluster'
        - PolicyName: S3ReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub
                    - '${BucketArn}/*'
                    - BucketArn:
                        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-PromptsBucketArn'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-prompts-lambda'

  # CloudWatch Log Group for Lambda
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-restart-ecs-service'
      RetentionInDays: 7

  # Lambda Function
  RestartECSServiceFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-restart-ecs-service'
      Description: Restarts ECS service when prompts are updated in S3
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 60
      Environment:
        Variables:
          ECS_CLUSTER_NAME: !Sub '${ProjectName}-${Environment}-cluster'
          ECS_SERVICE_NAME: !Sub '${ProjectName}-${Environment}-backend'
          LOG_GROUP: !Ref LambdaLogGroup
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          from datetime import datetime

          # Initialize AWS clients
          ecs = boto3.client('ecs')
          logs = boto3.client('logs')

          # Environment variables
          CLUSTER_NAME = os.environ['ECS_CLUSTER_NAME']
          SERVICE_NAME = os.environ['ECS_SERVICE_NAME']
          LOG_GROUP = os.environ.get('LOG_GROUP', '/aws/lambda/restart-ecs-service')

          def lambda_handler(event, context):
              """
              Lambda function to restart ECS service when prompts are updated in S3.
              Triggered by S3 object PUT events.
              """

              print(f"Event received: {json.dumps(event)}")

              try:
                  # Extract S3 event details
                  for record in event['Records']:
                      event_name = record['eventName']
                      bucket_name = record['s3']['bucket']['name']
                      object_key = record['s3']['object']['key']

                      print(f"S3 Event: {event_name}")
                      print(f"Bucket: {bucket_name}")
                      print(f"Object: {object_key}")

                      # Only process PUT events (new uploads or updates)
                      if not event_name.startswith('ObjectCreated:'):
                          print(f"Ignoring event type: {event_name}")
                          continue

                      # Restart ECS service by forcing new deployment
                      print(f"Restarting ECS service: {SERVICE_NAME} in cluster: {CLUSTER_NAME}")

                      response = ecs.update_service(
                          cluster=CLUSTER_NAME,
                          service=SERVICE_NAME,
                          forceNewDeployment=True
                      )

                      print(f"Service update initiated successfully")
                      print(f"Service ARN: {response['service']['serviceArn']}")
                      print(f"Deployment ID: {response['service']['deployments'][0]['id']}")
                      print(f"Desired count: {response['service']['desiredCount']}")

                      # Log the update
                      log_message = {
                          'timestamp': datetime.utcnow().isoformat(),
                          'event': 'ECS_SERVICE_RESTART',
                          'reason': 'Prompts updated in S3',
                          'bucket': bucket_name,
                          'object_key': object_key,
                          'cluster': CLUSTER_NAME,
                          'service': SERVICE_NAME,
                          'deployment_id': response['service']['deployments'][0]['id']
                      }

                      print(f"Update completed: {json.dumps(log_message)}")

                  return {
                      'statusCode': 200,
                      'body': json.dumps({
                          'message': 'ECS service restart initiated successfully',
                          'cluster': CLUSTER_NAME,
                          'service': SERVICE_NAME
                      })
                  }

              except Exception as e:
                  error_message = f"Error restarting ECS service: {str(e)}"
                  print(error_message)

                  # Still return 200 to avoid S3 retries, but log the error
                  return {
                      'statusCode': 200,
                      'body': json.dumps({
                          'message': 'Error occurred',
                          'error': str(e)
                      })
                  }
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-restart-ecs-service'

  # Lambda Permission for S3 to invoke function
  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RestartECSServiceFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-PromptsBucketArn'
      SourceAccount: !Ref AWS::AccountId

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt RestartECSServiceFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-RestartECSLambdaArn'

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref RestartECSServiceFunction
    Export:
      Name: !Sub '${ProjectName}-${Environment}-RestartECSLambdaName'

  LambdaLogGroupName:
    Description: CloudWatch Log Group for Lambda
    Value: !Ref LambdaLogGroup
    Export:
      Name: !Sub '${ProjectName}-${Environment}-RestartECSLambdaLogGroup'
